# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlightPlannerPW
                                 A QGIS plugin
 WUT plugin version
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-12
        copyright            : (C) 2025 by J. Białas, Sz. Węgliński
        email                : szymon.weglinski.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlightPlannerPW class from file FlightPlannerPW.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flight_planner_v1 import FlightPlannerPW
    return FlightPlannerPW(iface)
